### ISSUE TITLE
A booting issue in the veraison example with HES

### ISSUE THREAD

**Issue by zpzigi754** [islet-project/islet#392] opened 2024-11-01 07:50 UTC
I've tried to follow the steps in [veraison guide](https://github.com/islet-project/islet/blob/main/examples/veraison/RUN.md).

For some reasons, if I run `./scripts/fvp-cca --normal-world=linux --realm=linux --rmm=islet --hes --rmm-log-level info`, the booting does not succeed, as it is stuck with the following logs.

```
NOTICE:  Booting Trusted Firmware
NOTICE:  BL1: v2.10.0   (release):0b72924
NOTICE:  BL1: Built : 16:09:33, Nov  1 2024
NOTICE:  Measured boot extend measurement:
NOTICE:   - slot        : 6
NOTICE:   - signer_id   : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
NOTICE:   - version     :
NOTICE:   - version_size: 0
NOTICE:   - sw_type     : FW_CONFIG
NOTICE:   - sw_type_size: 10
NOTICE:   - algorithm   : 2000009
NOTICE:   - measurement : 0f 00 bd d3 8f c2 01 e9 94 cb d7 f5 3f 58 18 dd
 33 bd fa 45 15 62 b6 52 70 14 7e ec b7 f4 61 e4
NOTICE:   - locking     : true
NOTICE:  [RSS_SERIAL] protocol: EMBED
NOTICE:  [RSS_SERIAL] Serial initialized
NOTICE:  [RSS_SERIAL] sent 116 bytes
```

If I do not use `--hes` option (e.g., executing `$scripts/tests/realm-boot.sh`), the booting would succeed.

**Comment by zpzigi754** [comment] 2024-11-01 08:17
It seems that there is an issue between `hes` and `telnet`. If I pass `--no-telnet` option like (`./scripts/fvp-cca --normal-world=linux --realm=linux --rmm=islet --hes --rmm-log-level info --no-telnet`), the stuck symptom disappears (the booting succeeds).

**Comment by bokdeuk-jeong** [comment] 2024-11-04 04:10
@p-sawicki2 
could you take a look into this?

**Comment by p-sawicki2** [comment] 2024-11-04 06:58
@Havner Could you please check that?

**Comment by L0czek** [comment] 2024-11-05 11:04
@zpzigi754 I merged https://github.com/islet-project/islet/pull/367 and can't reporduce your issue. Please update your local repository and try again.

**Comment by Havner** [comment] 2024-11-05 11:36
I also can't reproduce it (I don't think #367 is relevant here) but I have a suspicion what might be the culprit. I'll make a PR in a sec.

**Closed** 2024-11-11 06:16 UTC
